<x-filament-panels::page>
    <x-filament::section>
        <form wire:submit="runTests">
            {{ $this->form }}
            <div class="mt-4 flex justify-end">
                <x-filament::button type="submit" wire:loading.attr="disabled">
                    Run Actual Newman Suite
                </x-filament::button>
            </div>
        </form>
    </x-filament::section>

    @if($reportUrl)
        <x-filament::section title="Newman HTML Report" class="mt-6">
            <div class="flex justify-between items-center mb-4">
                <p class="text-sm text-gray-500">The report below is generated by the Newman engine.</p>
                <x-filament::button href="{{ $reportUrl }}" tag="a" target="_blank" color="gray" icon="heroicon-m-arrow-top-right-on-square">
                    Open Full Report
                </x-filament::button>
            </div>
            
            <iframe 
                src="{{ $reportUrl }}" 
                style="border: none; width: 100%; height: 100vh; display: block;"
                sandbox="allow-scripts allow-same-origin allow-popups"
                loading="lazy"
            ></iframe>
        </x-filament::section>
    @endif
</x-filament-panels::page>